version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0
  circleci-cli: circleci/circleci-cli@0.1.8

jobs:

  publish-prod:
    executor: circleci-cli/default
    steps:
      - checkout
      - run:
          name: Get Tag
          command: |
            echo 'export VERSION=${CIRCLE_TAG//v/}' >> $BASH_ENV
      - orb-tools/publish:
         orb-path: src/orb.yml
         orb-ref: orbbant/helloworld@$VERSION

  create-orb:
    executor: circleci-cli/default
    steps:
      - run:
          name: Create orb if doesnt exist
          command: |
            circleci orb create orbbant/helloworld --no-prompt --token $CIRCLE_TOKEN || echo 'orb already exists'

workflows:
  dev-publish:
    jobs:
      - create-orb
      - orb-tools/publish-dev:
          checkout: true
          attach-workspace: false
          orb-name: orbbant/helloworld
          orb-path: src/orb.yml
          publish-alpha-version: false
          validate: true
          store-artifact: false
          requires:
            - create-orb
  dev-prod:
    jobs:
      - publish-prod:
          filters:
            tags:
              only: /^v(\d+\.\d+.\d+)$/
            branches:
              ignore: /.*/
