version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0
  circleci-cli: circleci/circleci-cli@0.1.8

jobs:
  publish-prod:
    executor: circleci-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Generate Version Tag
          command: echo 'export VERSION=${CIRCLE_TAG//v/}' >> $BASH_ENV
      - orb-tools/publish:
          orb-ref: orbbant/helloworld@$VERSION
          orb-path: workspace/orb.yml

workflows:
  build-and-deploy:
    jobs:
      - orb-tools/pack:
        # validation is done inside app
          filters:
            tags:
              only: /^v(\d+\.\d+.\d+)$/
      - orb-tools/publish-dev:
          # release dev version of orb, for testing & possible publishing.
          # orb will be published as dev:${CIRCLE_SHA1:0:7}.
          orb-name: orbbant/helloworld
          publish-alpha-version: false
          store-artifact: false
          requires:
            - orb-tools/pack
      - publish-prod:
          requires:
            - orb-tools/pack
          filters:
            tags:
              only: /^v(\d+\.\d+.\d+)$/
            branches:
              ignore: /.*/
