version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0
  circleci-cli: circleci/circleci-cli@0.1.8

jobs:
  publish-prod:
    executor: circleci-cli/default
    parameters:
      orb-name:
        type: string
    steps:
      - checkout
      - run:
          name: Get Tag
          command: |
            echo 'export VERSION=${CIRCLE_TAG//v/}' >> $BASH_ENV
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: <<parameters.orb-name>>@$VERSION

  create-orb-if-not-exist:
    executor: circleci-cli/default
    parameters:
      orb-name:
        type: string
    steps:
      - checkout
      - run:
          name: Create orb if doesnt exist
          command: |
            circleci orb create <<parameters.orb-name>> --token $CIRCLE_TOKEN --no-prompt
            VAR=$?
            if [ $VAR == 255 ]
            then
                echo "orbbant/helloworld13 already exists"
                exit 0
            fi

  publish-dev:
    executor: circleci-cli/default
    parameters:
      orb-name:
        type: string
    steps:
      - checkout
      # - run:
      #     name: Create orb if doesnt exist
      #     command: |
      #       circleci orb create <<parameters.orb-name>> --no-prompt --token $CIRCLE_TOKEN || echo 'orb already exists'
      # check other commit
      - orb-tools/validate:
          orb-path: src/orb.yml
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: <<parameters.orb-name>>@dev:${CIRCLE_SHA1:0:7}
      - run:
          name: Source code of published dev orb
          command: circleci orb source <<parameters.orb-name>>@dev:${CIRCLE_SHA1:0:7}

workflows:

  dev-publish:
    jobs:
      - create-orb-if-not-exist:
          orb-name: orbbant/helloworld15
      - publish-dev:
          orb-name: orbbant/helloworld15
          requires:
            - create-orb-if-not-exist

  prod-publish:
    jobs:
      - publish-prod:
          orb-name: orbbant/helloworld15
          filters:
            tags:
              only: /^v(\d+\.\d+.\d+)$/
            branches:
              ignore: /.*/
