version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0
  circleci-cli: circleci/circleci-cli@0.1.8

jobs:
  publish-prod:
    executor: circleci-cli/default
    steps:
      - checkout
      - run:
          name: Get Tag
          command: |
            echo 'export VERSION=${CIRCLE_TAG//v/}' >> $BASH_ENV
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: orbbant/helloworld@$VERSION

  publish-dev:
    executor: circleci-cli/default
    steps:
      - checkout
      - run:
          name: Create orb if doesnt exist
          command: |
            circleci orb create orbbant/helloworld --no-prompt --token $CIRCLE_TOKEN || echo 'orb already exists'
      - orb-tools/validate:
          orb-path: src/orb.yml
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: orbbant/helloworld@dev:${CIRCLE_SHA1:0:7}
      - run:
          name: Source code of published orb
          command: circleci orb source orbbant/helloworld@dev:${CIRCLE_SHA1:0:7}

workflows:
  dev-publish:
    jobs:
      - publish-dev
  dev-prod:
    jobs:
      - publish-prod:
          filters:
            tags:
              only: /^v(\d+\.\d+.\d+)$/
            branches:
              ignore: /.*/
