version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0
  circleci-cli: circleci/circleci-cli@0.1.8

jobs:
  publish-prod:
    parameters:
      orb-name:
        type: string
    executor: circleci-cli/default
    steps:
      - checkout
      - run:
          name: Get Tag
          command: |
            echo 'export VERSION=${CIRCLE_TAG//v/}' >> $BASH_ENV
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: <<parameteres.orb-name>>@$VERSION

  publish-dev:
    parameters:
      orb-name:
        type: string
    executor: circleci-cli/default
    steps:
      - checkout
      - run:
          name: Create orb if doesnt exist
          command: |
            circleci orb create <<parameteres.orb-name>> --no-prompt --token $CIRCLE_TOKEN || echo 'orb already exists'
      - orb-tools/validate:
          orb-path: src/orb.yml
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: <<parameteres.orb-name>>@dev:${CIRCLE_SHA1:0:7}
      - run:
          name: Source code of published dev orb
          command: circleci orb source <<parameteres.orb-name>>@dev:${CIRCLE_SHA1:0:7}

workflows:
  dev-publish:
    jobs:
      - publish-dev:
          orb-name: orbbant/helloworld

  dev-prod:
    jobs:
      - publish-prod:
          orb-name: orbbant/helloworld
          filters:
            tags:
              only: /^v(\d+\.\d+.\d+)$/
            branches:
              ignore: /.*/
