version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0.1.8
  orb-tools: circleci/orb-tools@9.1.0


workflows:
  dev-publish:
    jobs:
      - orb-tools/publish-dev:
          attach-workspace: false
          orb-name: orbbant/helloworld
          orb-path: /src/orb.yml
          publish-alpha-version: false
          validate: true
          store-artifact: false
