version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0

jobs:

  publish-prod:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - run:
          name: Get Tag
          command: |
            echo 'export VERSION=${CIRCLE_TAG//v/}' >> $BASH_ENV
      - orb-tools/publish:
         checkout: true
         orb-path: src/orb.yml
         orb-ref: orbbant/helloworld@$VERSION

workflows:
  dev-publish:
    jobs:
      - orb-tools/publish-dev:
          checkout: true
          attach-workspace: false
          orb-name: orbbant/helloworld
          orb-path: src/orb.yml
          publish-alpha-version: false
          validate: true
          store-artifact: false

  dev-prod:
    jobs:
      - publish-prod:
          filters:
            tags:
              only: /^v(\d+\.\d+.\d+)$/
            branches:
              ignore: /.*/
